{

  gROOT->Reset();
  gROOT->ProcessLine(".L tdrStyle.C");
  gROOT->ProcessLine("setTDRStyle()");
  gStyle->SetOptStat(0);

  TFile *_file_pu00 = TFile::Open("hitperiter_00PU50ns.root");
  TFile *_file_pu20 = TFile::Open("hitperiter_20PU50ns.root");
  TFile *_file_pu40 = TFile::Open("hitperiter_40PU50ns.root");
  TFile *_file_pu60 = TFile::Open("hitperiter_60PU50ns.root");

  bool domaskplots = 0; 
  bool domatchplot = 0;
  bool doghostplot = 1;

  if (domaskplots) {

    //all barrel hits plot
    TCanvas c_barrel;
    TH1F* pixel_pxb1_pu20 = (TH1F*) _file_pu20->Get("demo/pixel_pxb1");
    pixel_pxb1_pu20->SetLineWidth(2);
    pixel_pxb1_pu20->SetLineColor(kRed);
    pixel_pxb1_pu20->Scale(1./pixel_pxb1_pu20->GetBinContent(1));
    pixel_pxb1_pu20->GetXaxis()->SetRangeUser(0,7);
    pixel_pxb1_pu20->GetYaxis()->SetRangeUser(0,1.05);
    pixel_pxb1_pu20->GetYaxis()->SetTitle("fraction of unmasked hits");
    pixel_pxb1_pu20->SetTitle("");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(1,"iter0");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(2,"iter1");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(3,"iter2");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(4,"iter3");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(5,"iter4");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(6,"iter5");
    pixel_pxb1_pu20->GetXaxis()->SetBinLabel(7,"iter6");
    pixel_pxb1_pu20->GetYaxis()->SetTitleOffset(1.2);
    pixel_pxb1_pu20->GetYaxis()->SetTitleSize(0.05);
    pixel_pxb1_pu20->GetYaxis()->SetLabelSize(0.05);
    pixel_pxb1_pu20->GetXaxis()->SetTitleOffset(1.1);
    pixel_pxb1_pu20->GetXaxis()->SetTitleSize(0.05);
    pixel_pxb1_pu20->GetXaxis()->SetLabelSize(0.06);
    TH1F* rphi_tib1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tib1");
    rphi_tib1_pu20->SetLineWidth(2);
    rphi_tib1_pu20->SetLineColor(kBlue);
    rphi_tib1_pu20->Scale(1./rphi_tib1_pu20->GetBinContent(1));
    TH1F* rphi_tob1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tob1");
    rphi_tob1_pu20->SetLineWidth(2);
    rphi_tob1_pu20->SetLineColor(kMagenta);
    rphi_tob1_pu20->Scale(1./rphi_tob1_pu20->GetBinContent(1));
    pixel_pxb1_pu20->Draw();
    rphi_tib1_pu20->Draw("same");
    rphi_tob1_pu20->Draw("same");
    TLegend* leg = new TLegend(0.73,0.25,0.93,0.42);
    leg->SetNColumns(1);
    leg->SetFillColor(kWhite);
    leg->SetLineColor(kWhite);
    leg->SetShadowColor(kWhite);
    leg->SetBorderSize(0);
    leg->SetTextFont(42);
    leg->SetTextSize(0.05);
    leg->AddEntry(pixel_pxb1_pu20,"PXB1","L");
    leg->AddEntry(rphi_tib1_pu20,"TIB1","L");
    leg->AddEntry(rphi_tob1_pu20,"TOB1","L");
    TPaveText* labelcms  = new TPaveText(0.21,0.28,0.65,0.42,"NDCBR");
    labelcms->SetTextAlign(12);
    labelcms->SetTextSize(0.040);
    labelcms->SetFillColor(kWhite);
    labelcms->AddText("CMS Preliminary Simulation");
    labelcms->AddText("#sqrt{s} = 8 TeV, t#bar{t} + <PU>=20");
    labelcms->SetBorderSize(0);
    labelcms->SetTextFont(42);
    labelcms->SetLineWidth(2);
    leg->Draw();labelcms->Draw();
    c_barrel.SetGridx();
    c_barrel.SaveAs("barrel_hits_per_iter_pu20.png");

    //all forward hits plot
    TCanvas c_forward;
    TH1F* pixel_pxf1_pu20 = (TH1F*) _file_pu20->Get("demo/pixel_pxf1");
    pixel_pxf1_pu20->SetLineWidth(2);
    pixel_pxf1_pu20->SetLineColor(kRed);
    pixel_pxf1_pu20->Scale(1./pixel_pxf1_pu20->GetBinContent(1));
    pixel_pxf1_pu20->GetXaxis()->SetRangeUser(0,7);
    pixel_pxf1_pu20->GetYaxis()->SetRangeUser(0,1.05);
    pixel_pxf1_pu20->GetYaxis()->SetTitle("fraction of unmasked hits");
    pixel_pxf1_pu20->SetTitle("");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(1,"iter0");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(2,"iter1");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(3,"iter2");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(4,"iter3");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(5,"iter4");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(6,"iter5");
    pixel_pxf1_pu20->GetXaxis()->SetBinLabel(7,"iter6");
    pixel_pxf1_pu20->GetYaxis()->SetTitleOffset(1.2);
    pixel_pxf1_pu20->GetYaxis()->SetTitleSize(0.05);
    pixel_pxf1_pu20->GetYaxis()->SetLabelSize(0.05);
    pixel_pxf1_pu20->GetXaxis()->SetTitleOffset(1.1);
    pixel_pxf1_pu20->GetXaxis()->SetTitleSize(0.05);
    pixel_pxf1_pu20->GetXaxis()->SetLabelSize(0.06);
    TH1F* rphi_tid1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tid1");
    rphi_tid1_pu20->SetLineWidth(2);
    rphi_tid1_pu20->SetLineColor(kBlue);
    rphi_tid1_pu20->Scale(1./rphi_tid1_pu20->GetBinContent(1));
    TH1F* rphi_tec1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tec1");
    rphi_tec1_pu20->SetLineWidth(2);
    rphi_tec1_pu20->SetLineColor(kMagenta);
    rphi_tec1_pu20->Scale(1./rphi_tec1_pu20->GetBinContent(1));
    pixel_pxf1_pu20->Draw();
    rphi_tid1_pu20->Draw("same");
    rphi_tec1_pu20->Draw("same");
    TLegend* leg = new TLegend(0.73,0.25,0.93,0.42);
    leg->SetNColumns(1);
    leg->SetFillColor(kWhite);
    leg->SetLineColor(kWhite);
    leg->SetShadowColor(kWhite);
    leg->SetBorderSize(0);
    leg->SetTextFont(42);
    leg->SetTextSize(0.05);
    leg->AddEntry(pixel_pxf1_pu20,"PXF1","L");
    leg->AddEntry(rphi_tid1_pu20,"TID1","L");
    leg->AddEntry(rphi_tec1_pu20,"TEC1","L");
    TPaveText* labelcms  = new TPaveText(0.21,0.28,0.65,0.42,"NDCBR");
    labelcms->SetTextAlign(12);
    labelcms->SetTextSize(0.040);
    labelcms->SetFillColor(kWhite);
    labelcms->AddText("CMS Preliminary Simulation");
    labelcms->AddText("#sqrt{s} = 8 TeV, t#bar{t} + <PU>=20");
    labelcms->SetBorderSize(0);
    labelcms->SetTextFont(42);
    labelcms->SetLineWidth(2);
    leg->Draw();labelcms->Draw();
    c_forward.SetGridx();
    c_forward.SaveAs("forward_hits_per_iter_pu20.png");

  } else if (domatchplot) {

    TCanvas c_mtch_tib1_pu;
    TH1F* mtch_tib1_pu20 = (TH1F*) _file_pu20->Get("demo/mtch_tib1");
    mtch_tib1_pu20->SetLineWidth(2);
    mtch_tib1_pu20->SetLineColor(kBlack);
    mtch_tib1_pu20->SetLineStyle(3);
    float pu20bin1 = mtch_tib1_pu20->GetBinContent(1);
    mtch_tib1_pu20->Scale(1./pu20bin1);
    mtch_tib1_pu20->GetXaxis()->SetRangeUser(0,7);
    mtch_tib1_pu20->GetYaxis()->SetRangeUser(0,5);
    mtch_tib1_pu20->GetYaxis()->SetTitle("number of TIB1 hits [1/<PU>=20]");
    mtch_tib1_pu20->SetTitle("");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(1,"iter0");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(2,"iter1");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(3,"iter2");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(4,"iter3");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(5,"iter4");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(6,"iter5");
    mtch_tib1_pu20->GetXaxis()->SetBinLabel(7,"iter6");
    mtch_tib1_pu20->GetYaxis()->SetTitleOffset(1.2);
    mtch_tib1_pu20->GetYaxis()->SetTitleSize(0.045);
    mtch_tib1_pu20->GetYaxis()->SetLabelSize(0.04);
    mtch_tib1_pu20->GetXaxis()->SetTitleOffset(1.1);
    mtch_tib1_pu20->GetXaxis()->SetLabelSize(0.06);
    TH1F* mtch_tib1_pu40 = (TH1F*) _file_pu40->Get("demo/mtch_tib1");
    mtch_tib1_pu40->SetLineWidth(2);
    mtch_tib1_pu40->SetLineColor(kBlack);
    mtch_tib1_pu40->SetLineStyle(1);
    mtch_tib1_pu40->Scale(1./pu20bin1);
    TH1F* mtch_tib1_pu60 = (TH1F*) _file_pu60->Get("demo/mtch_tib1");
    mtch_tib1_pu60->SetLineWidth(2);
    mtch_tib1_pu60->SetLineColor(kBlack);
    mtch_tib1_pu60->SetLineStyle(7);
    mtch_tib1_pu60->Scale(1./pu20bin1);
    TH1F* rphi_tib1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tib1");
    rphi_tib1_pu20->SetLineWidth(2);
    rphi_tib1_pu20->SetLineColor(kRed);
    rphi_tib1_pu20->SetLineStyle(3);
    float rp_pu20bin1 = rphi_tib1_pu20->GetBinContent(1);
    rphi_tib1_pu20->Scale(1./rp_pu20bin1);
    rphi_tib1_pu20->GetXaxis()->SetRangeUser(0,7);
    rphi_tib1_pu20->GetYaxis()->SetRangeUser(0,5);
    rphi_tib1_pu20->SetTitle("");
    TH1F* rphi_tib1_pu40 = (TH1F*) _file_pu40->Get("demo/rphi_tib1");
    rphi_tib1_pu40->SetLineWidth(2);
    rphi_tib1_pu40->SetLineColor(kRed);
    rphi_tib1_pu40->SetLineStyle(1);
    rphi_tib1_pu40->Scale(1./rp_pu20bin1);
    TH1F* rphi_tib1_pu60 = (TH1F*) _file_pu60->Get("demo/rphi_tib1");
    rphi_tib1_pu60->SetLineWidth(2);
    rphi_tib1_pu60->SetLineColor(kRed);
    rphi_tib1_pu60->SetLineStyle(7);
    rphi_tib1_pu60->Scale(1./rp_pu20bin1);
    mtch_tib1_pu20->Draw();
    mtch_tib1_pu40->Draw("same");
    mtch_tib1_pu60->Draw("same");
    rphi_tib1_pu20->Draw("same");
    rphi_tib1_pu40->Draw("same");
    rphi_tib1_pu60->Draw("same");
    TLegend* leg = new TLegend(0.57,0.65,0.93,0.92);
    leg->SetNColumns(1);
    leg->SetFillColor(kWhite);
    leg->SetLineColor(kWhite);
    leg->SetShadowColor(kWhite);
    leg->SetBorderSize(0);
    leg->SetTextFont(42);
    leg->SetTextSize(0.035);
    leg->AddEntry(rphi_tib1_pu20,"mono <PU>=20","L");
    leg->AddEntry(rphi_tib1_pu40,"mono <PU>=40","L");
    leg->AddEntry(rphi_tib1_pu60,"mono <PU>=60","L");
    leg->AddEntry(mtch_tib1_pu20,"match <PU>=20","L");
    leg->AddEntry(mtch_tib1_pu40,"match <PU>=40","L");
    leg->AddEntry(mtch_tib1_pu60,"match <PU>=60","L");
    TPaveText* labelcms  = new TPaveText(0.15,0.80,0.40,0.92,"NDCBR");
    labelcms->SetTextAlign(12);
    labelcms->SetTextSize(0.035);
    labelcms->SetFillColor(kWhite);
    labelcms->AddText("CMS Preliminary Simulation");
    labelcms->AddText("#sqrt{s} = 8 TeV, t#bar{t}");
    labelcms->SetBorderSize(0);
    labelcms->SetTextFont(42);
    labelcms->SetLineWidth(2);
    leg->Draw();labelcms->Draw();
    c_mtch_tib1_pu.SetGridx();
    c_mtch_tib1_pu.SaveAs("mtch_tib1_per_iter_pu.png");

  } else if {doghostplot) {

    bool donew = 1;

    TCanvas c_ghost_pu;
    TH1F* mtch_tib1_pu00 = (TH1F*) _file_pu00->Get("demo/mtch_tib1");
    TH1F* mtch_tib1_pu20 = (TH1F*) _file_pu20->Get("demo/mtch_tib1");
    TH1F* mtch_tib1_pu40 = (TH1F*) _file_pu40->Get("demo/mtch_tib1");
    TH1F* mtch_tib1_pu60 = (TH1F*) _file_pu60->Get("demo/mtch_tib1");
    TH1F* rphi_tib1_pu00 = (TH1F*) _file_pu00->Get("demo/rphi_tib1");
    TH1F* rphi_tib1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tib1");
    TH1F* rphi_tib1_pu40 = (TH1F*) _file_pu40->Get("demo/rphi_tib1");
    TH1F* rphi_tib1_pu60 = (TH1F*) _file_pu60->Get("demo/rphi_tib1");
    TH1F* mtch_tib2_pu00 = (TH1F*) _file_pu00->Get("demo/mtch_tib2");
    TH1F* mtch_tib2_pu20 = (TH1F*) _file_pu20->Get("demo/mtch_tib2");
    TH1F* mtch_tib2_pu40 = (TH1F*) _file_pu40->Get("demo/mtch_tib2");
    TH1F* mtch_tib2_pu60 = (TH1F*) _file_pu60->Get("demo/mtch_tib2");
    TH1F* rphi_tib2_pu00 = (TH1F*) _file_pu00->Get("demo/rphi_tib2");
    TH1F* rphi_tib2_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tib2");
    TH1F* rphi_tib2_pu40 = (TH1F*) _file_pu40->Get("demo/rphi_tib2");
    TH1F* rphi_tib2_pu60 = (TH1F*) _file_pu60->Get("demo/rphi_tib2");
    TH1F* mtch_tob1_pu00 = (TH1F*) _file_pu00->Get("demo/mtch_tob1");
    TH1F* mtch_tob1_pu20 = (TH1F*) _file_pu20->Get("demo/mtch_tob1");
    TH1F* mtch_tob1_pu40 = (TH1F*) _file_pu40->Get("demo/mtch_tob1");
    TH1F* mtch_tob1_pu60 = (TH1F*) _file_pu60->Get("demo/mtch_tob1");
    TH1F* rphi_tob1_pu00 = (TH1F*) _file_pu00->Get("demo/rphi_tob1");
    TH1F* rphi_tob1_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tob1");
    TH1F* rphi_tob1_pu40 = (TH1F*) _file_pu40->Get("demo/rphi_tob1");
    TH1F* rphi_tob1_pu60 = (TH1F*) _file_pu60->Get("demo/rphi_tob1");
    TH1F* mtch_tob2_pu00 = (TH1F*) _file_pu00->Get("demo/mtch_tob2");
    TH1F* mtch_tob2_pu20 = (TH1F*) _file_pu20->Get("demo/mtch_tob2");
    TH1F* mtch_tob2_pu40 = (TH1F*) _file_pu40->Get("demo/mtch_tob2");
    TH1F* mtch_tob2_pu60 = (TH1F*) _file_pu60->Get("demo/mtch_tob2");
    TH1F* rphi_tob2_pu00 = (TH1F*) _file_pu00->Get("demo/rphi_tob2");
    TH1F* rphi_tob2_pu20 = (TH1F*) _file_pu20->Get("demo/rphi_tob2");
    TH1F* rphi_tob2_pu40 = (TH1F*) _file_pu40->Get("demo/rphi_tob2");
    TH1F* rphi_tob2_pu60 = (TH1F*) _file_pu60->Get("demo/rphi_tob2");
    TH1F* ghost_pu20 = new TH1F("","",4,0,4);
    ghost_pu20->GetXaxis()->SetBinLabel(1,"TIB1");
    ghost_pu20->GetXaxis()->SetBinLabel(2,"TIB2");
    ghost_pu20->GetXaxis()->SetBinLabel(3,"TOB1");
    ghost_pu20->GetXaxis()->SetBinLabel(4,"TOB2");
    TH1F* ghost_pu00 = ghost_pu20->Clone("ghost_pu00");
    TH1F* ghost_pu40 = ghost_pu20->Clone("ghost_pu40");
    TH1F* ghost_pu60 = ghost_pu20->Clone("ghost_pu60");
    if (!donew) {
      ghost_pu00->SetBinContent(1,1.-rphi_tib1_pu00->GetBinContent(1)/mtch_tib1_pu00->GetBinContent(1));
      ghost_pu00->SetBinContent(2,1.-rphi_tib2_pu00->GetBinContent(1)/mtch_tib2_pu00->GetBinContent(1));
      ghost_pu00->SetBinContent(3,1.-rphi_tob1_pu00->GetBinContent(1)/mtch_tob1_pu00->GetBinContent(1));
      ghost_pu00->SetBinContent(4,1.-rphi_tob2_pu00->GetBinContent(1)/mtch_tob2_pu00->GetBinContent(1));
      ghost_pu20->SetBinContent(1,1.-rphi_tib1_pu20->GetBinContent(1)/mtch_tib1_pu20->GetBinContent(1));
      ghost_pu20->SetBinContent(2,1.-rphi_tib2_pu20->GetBinContent(1)/mtch_tib2_pu20->GetBinContent(1));
      ghost_pu20->SetBinContent(3,1.-rphi_tob1_pu20->GetBinContent(1)/mtch_tob1_pu20->GetBinContent(1));
      ghost_pu20->SetBinContent(4,1.-rphi_tob2_pu20->GetBinContent(1)/mtch_tob2_pu20->GetBinContent(1));
      ghost_pu40->SetBinContent(1,1.-rphi_tib1_pu40->GetBinContent(1)/mtch_tib1_pu40->GetBinContent(1));
      ghost_pu40->SetBinContent(2,1.-rphi_tib2_pu40->GetBinContent(1)/mtch_tib2_pu40->GetBinContent(1));
      ghost_pu40->SetBinContent(3,1.-rphi_tob1_pu40->GetBinContent(1)/mtch_tob1_pu40->GetBinContent(1));
      ghost_pu40->SetBinContent(4,1.-rphi_tob2_pu40->GetBinContent(1)/mtch_tob2_pu40->GetBinContent(1));
      ghost_pu60->SetBinContent(1,1.-rphi_tib1_pu60->GetBinContent(1)/mtch_tib1_pu60->GetBinContent(1));
      ghost_pu60->SetBinContent(2,1.-rphi_tib2_pu60->GetBinContent(1)/mtch_tib2_pu60->GetBinContent(1));
      ghost_pu60->SetBinContent(3,1.-rphi_tob1_pu60->GetBinContent(1)/mtch_tob1_pu60->GetBinContent(1));
      ghost_pu60->SetBinContent(4,1.-rphi_tob2_pu60->GetBinContent(1)/mtch_tob2_pu60->GetBinContent(1));
      ghost_pu20->GetYaxis()->SetRangeUser(0.,1.0);
      ghost_pu20->GetYaxis()->SetTitle("fraction of ghost hits");
    } else {
      ghost_pu00->SetBinContent(1,mtch_tib1_pu00->GetBinContent(1)/rphi_tib1_pu00->GetBinContent(1)-1.);
      ghost_pu00->SetBinContent(2,mtch_tib2_pu00->GetBinContent(1)/rphi_tib2_pu00->GetBinContent(1)-1.);
      ghost_pu00->SetBinContent(3,mtch_tob1_pu00->GetBinContent(1)/rphi_tob1_pu00->GetBinContent(1)-1.);
      ghost_pu00->SetBinContent(4,mtch_tob2_pu00->GetBinContent(1)/rphi_tob2_pu00->GetBinContent(1)-1.);
      ghost_pu20->SetBinContent(1,mtch_tib1_pu20->GetBinContent(1)/rphi_tib1_pu20->GetBinContent(1)-1.);
      ghost_pu20->SetBinContent(2,mtch_tib2_pu20->GetBinContent(1)/rphi_tib2_pu20->GetBinContent(1)-1.);
      ghost_pu20->SetBinContent(3,mtch_tob1_pu20->GetBinContent(1)/rphi_tob1_pu20->GetBinContent(1)-1.);
      ghost_pu20->SetBinContent(4,mtch_tob2_pu20->GetBinContent(1)/rphi_tob2_pu20->GetBinContent(1)-1.);
      ghost_pu40->SetBinContent(1,mtch_tib1_pu40->GetBinContent(1)/rphi_tib1_pu40->GetBinContent(1)-1.);
      ghost_pu40->SetBinContent(2,mtch_tib2_pu40->GetBinContent(1)/rphi_tib2_pu40->GetBinContent(1)-1.);
      ghost_pu40->SetBinContent(3,mtch_tob1_pu40->GetBinContent(1)/rphi_tob1_pu40->GetBinContent(1)-1.);
      ghost_pu40->SetBinContent(4,mtch_tob2_pu40->GetBinContent(1)/rphi_tob2_pu40->GetBinContent(1)-1.);
      ghost_pu60->SetBinContent(1,mtch_tib1_pu60->GetBinContent(1)/rphi_tib1_pu60->GetBinContent(1)-1.);
      ghost_pu60->SetBinContent(2,mtch_tib2_pu60->GetBinContent(1)/rphi_tib2_pu60->GetBinContent(1)-1.);
      ghost_pu60->SetBinContent(3,mtch_tob1_pu60->GetBinContent(1)/rphi_tob1_pu60->GetBinContent(1)-1.);
      ghost_pu60->SetBinContent(4,mtch_tob2_pu60->GetBinContent(1)/rphi_tob2_pu60->GetBinContent(1)-1.);
      ghost_pu20->GetYaxis()->SetRangeUser(0.,2.5);
      ghost_pu20->GetYaxis()->SetTitle("N_{ghost}/N_{mono}");
    }
    ghost_pu20->SetLineWidth(2);
    ghost_pu20->SetLineColor(kBlack);
    ghost_pu20->SetLineStyle(3);
    ghost_pu20->SetTitle("");
    ghost_pu20->GetYaxis()->SetTitleOffset(1.2);
    ghost_pu20->GetYaxis()->SetTitleSize(0.045);
    ghost_pu20->GetYaxis()->SetLabelSize(0.04);
    ghost_pu20->GetXaxis()->SetTitleOffset(1.1);
    ghost_pu20->GetXaxis()->SetLabelSize(0.06);
    ghost_pu00->SetLineWidth(2);
    ghost_pu00->SetLineColor(kBlack);
    ghost_pu00->SetLineStyle(4);
    ghost_pu40->SetLineWidth(2);
    ghost_pu40->SetLineColor(kBlack);
    ghost_pu40->SetLineStyle(1);
    ghost_pu60->SetLineWidth(2);
    ghost_pu60->SetLineColor(kBlack);
    ghost_pu60->SetLineStyle(7);
    ghost_pu20->Draw();
    ghost_pu00->Draw("same");
    ghost_pu40->Draw("same");
    ghost_pu60->Draw("same");
    TLegend* leg = new TLegend(0.65,0.68,0.92,0.94);
    leg->SetNColumns(1);
    leg->SetFillColor(kWhite);
    leg->SetLineColor(kWhite);
    leg->SetShadowColor(kWhite);
    leg->SetBorderSize(0);
    leg->SetTextFont(42);
    leg->SetTextSize(0.035);
    leg->AddEntry(ghost_pu00,"no PU","L");
    leg->AddEntry(ghost_pu20,"<PU>=20","L");
    leg->AddEntry(ghost_pu40,"<PU>=40","L");
    leg->AddEntry(ghost_pu60,"<PU>=60","L");
    TPaveText* labelcms  = new TPaveText(0.15,0.80,0.40,0.92,"NDCBR");
    labelcms->SetTextAlign(12);
    labelcms->SetTextSize(0.038);
    labelcms->SetFillColor(kWhite);
    labelcms->AddText("CMS Preliminary Simulation");
    labelcms->AddText("#sqrt{s} = 8 TeV, t#bar{t}");
    labelcms->SetBorderSize(0);
    labelcms->SetTextFont(42);
    labelcms->SetLineWidth(2);
    leg->Draw();labelcms->Draw();
    c_ghost_pu.SetGridx();
    if (!donew) c_ghost_pu.SaveAs("ghost_pu.png");
    else c_ghost_pu.SaveAs("ghost_pu_new.png");

  }
}
}
